//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAMS_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminAccountDoctorDentist
    {
        public int ID { get; set; }
        public int DoctorDentistID { get; set; }
        public int AdminID { get; set; }
    
        public virtual AdminAccount AdminAccount { get; set; }
        public virtual DoctorDentist DoctorDentist { get; set; }
    }
}
