//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAMS_03.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DAMS_01Entities : DbContext
    {
        public DAMS_01Entities()
            : base("name=DAMS_01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminAccount> AdminAccounts { get; set; }
        public virtual DbSet<AdminAccountClinicHospital> AdminAccountClinicHospitals { get; set; }
        public virtual DbSet<Advertisement> Advertisements { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AppointmentTreatment> AppointmentTreatments { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<ClinicHospital> ClinicHospitals { get; set; }
        public virtual DbSet<ClinicHospitalAdvertisement> ClinicHospitalAdvertisements { get; set; }
        public virtual DbSet<ClinicHospitalTreatment> ClinicHospitalTreatments { get; set; }
        public virtual DbSet<DoctorDentist> DoctorDentists { get; set; }
        public virtual DbSet<DoctorDentistDateBooking> DoctorDentistDateBookings { get; set; }
        public virtual DbSet<OpeningHour> OpeningHours { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
    }
}
