#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Dental_IT.Droid.Resource", IsApplication=true)]

namespace Dental_IT.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060002
			public const int _5_white = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int _8_white = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int black = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int blue = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int dark_blue = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int transparent = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int white = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int editText_line = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int login_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int login_box = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int text_selector = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int mainMenu_GridView = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int register_DOBField = 2131034117;
			
			// aapt resource value: 0x7f050015
			public const int register_DentistDropdown = 2131034133;
			
			// aapt resource value: 0x7f050002
			public const int register_EmailField = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int register_GenderDropdown = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int register_MobileField = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int register_NRICField = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int register_PasswordField = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int register_PdpaChkbox = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int register_PdpaLayout = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int register_PdpaText = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int register_RegisterBtn = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int register_RepeatPasswordField = 2131034116;
			
			// aapt resource value: 0x7f050018
			public const int register_SessionDropdown = 2131034136;
			
			// aapt resource value: 0x7f050012
			public const int request_DateField = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int request_DateLayout = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int request_DateText = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int request_DentistLayout = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int request_DentistText = 2131034132;
			
			// aapt resource value: 0x7f05000f
			public const int request_HospitalField = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int request_HospitalLayout = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int request_HospitalText = 2131034126;
			
			// aapt resource value: 0x7f05001c
			public const int request_RemarksField = 2131034140;
			
			// aapt resource value: 0x7f05001a
			public const int request_RemarksLayout = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int request_RemarksText = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int request_RequestBtn = 2131034141;
			
			// aapt resource value: 0x7f050016
			public const int request_SessionLayout = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int request_SessionText = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int request_TreatmentsBtn = 2131034137;
			
			// aapt resource value: 0x7f050025
			public const int selectHospital_FavouritesToggle = 2131034149;
			
			// aapt resource value: 0x7f050024
			public const int selectHospital_HospitalText = 2131034148;
			
			// aapt resource value: 0x7f05001e
			public const int selectHospital_RecyclerView = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int signIn_EmailField = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int signIn_PasswordField = 2131034144;
			
			// aapt resource value: 0x7f050023
			public const int signIn_RegisterText = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int signIn_RememberMeChkbox = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int signIn_SignInBtn = 2131034145;
			
			// aapt resource value: 0x7f050026
			public const int spinnerItem = 2131034150;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main_Menu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Register = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Request_Appointment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Select_Hospital = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Sign_In = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int sublayout_Hospital_List_Item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int sublayout_Spinner_View = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070007
			public const int DOB = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int NRIC = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070011
			public const int date = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int dentist = 2131165203;
			
			// aapt resource value: 0x7f070001
			public const int email = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int gender = 2131165192;
			
			// aapt resource value: 0x7f07000f
			public const int hospital = 2131165199;
			
			// aapt resource value: 0x7f07000a
			public const int mobile = 2131165194;
			
			// aapt resource value: 0x7f070002
			public const int password = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int pdpa = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int pdpa_text = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int pdpa_title = 2131165196;
			
			// aapt resource value: 0x7f070010
			public const int pref_date = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int pref_dentist = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int pref_session = 2131165204;
			
			// aapt resource value: 0x7f07000e
			public const int register = 2131165198;
			
			// aapt resource value: 0x7f070005
			public const int register_text = 2131165189;
			
			// aapt resource value: 0x7f070017
			public const int remarks = 2131165207;
			
			// aapt resource value: 0x7f070004
			public const int remember_me = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int repeat_password = 2131165190;
			
			// aapt resource value: 0x7f070015
			public const int session = 2131165205;
			
			// aapt resource value: 0x7f070003
			public const int sign_in = 2131165187;
			
			// aapt resource value: 0x7f070018
			public const int submit = 2131165208;
			
			// aapt resource value: 0x7f070016
			public const int treatments = 2131165206;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
